### ISSUE TITLE
Le scrolling dans la modale de vote ne fonctionna pas sous firefox ! 

### ISSUE THREAD

**Issue by BenoitAverty** [ZenikaOuest/Democratie_Liquide_Front#4]
![2017-05-18-114343_1920x1008_scrot](https://cloud.githubusercontent.com/assets/17006335/26196449/3efff7ea-3bbf-11e7-8835-72cea2b16e4d.png)

**Comment by BenoitAverty** [comment]
@Waals

**Comment by Baloche** [comment]
Fixed with [11ab8c8](https://github.com/ZenikaOuest/Democratie_Liquide_Front/commit/11ab8c86332c1e8cd9df3cc5eaf01d7d4c4a8778)
