### ISSUE TITLE
Problème points négatifs sous Chrome

### ISSUE THREAD

**Issue by maici** [ZenikaOuest/Democratie_Liquide_Front#5]
Sous Chrome Version 58.0.3029.110 (64-bit) les points sont négatifs
![image](https://cloud.githubusercontent.com/assets/14937883/26196961/e5d3d626-3bc0-11e7-9050-eef9c4d3da7b.png)

**Comment by jeremiehuchet** [comment]
Pareil pour moi
```
Google Chrome | 61.0.3163.91 (Official Build) (64-bit)
-- | --
Revision | 2f544949507dc5330b714cb017e3f584e791a1bf-refs/branch-heads/3163@{#1194}
OS | Linux
JavaScript | V8 6.1.534.37
```

**Comment by Baloche** [comment]
Fixed by commit [b6fd347](https://github.com/ZenikaOuest/Democratie_Liquide_Front/commit/b6fd3470b28d0c04650dee7ee1c4857455b497d6)
